#include<stdio.h>
int main()
{
    int r,c,a[100][100],i,j,k,max=0,s,max1;
    scanf("%d%d",&r,&c);
    for(i=0;i<r;i++)
    {
        for(j=0;j<c;j++)
        {
            scanf("%d",&a[i][j]);
        }
    }
    for(i=0;i<r;i++)
    {
        k=0;
        for(j=0;j<c;j++)
        {
            k=k+a[i][j];
        }
        if(max<k)
        {
            max=k;
        }
    }
    for(j=0;j<c;j++)
    {
        s=0;
        for(i=0;i<r;i++)
        {
            s=s+a[i][j];
        }
        if(max1<s)
        {
            max1=s;
        }
    }
    if(max>max1)
    {
        printf("%d",max);
    }
    else
    {
        printf("%d",max1);
    }
    
}